Feature/homework 4 rxjava
eels911/MovieApp pull request #5
Opened 2023-01-08 17:46 UTC by eels911

2023-01-10 21:39 UTC, AndroidStudentClub requested changes
Проверил. круто что получилось сделать задание с поиском, но есть еще моменты для улучшения

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/build.gradle
> +            buildConfigField "String", "BASE_URL", "\"https://api.themoviedb.org/3/\""
👍

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/build.gradle
> +    implementation 'io.reactivex.rxjava3:rxjava:3.0.0'
Тут тоже в константы версию неплохо вынести было бы

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDto.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Кстати урл для картинки тоже можно вынести по аналогии с BASE_URL. Урлы для картинок конечно реже меняются - но в теории такое может быть. Да и к тому же тогда будет одна константа для всего и можно будет переиспользовать

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDto.kt
> +    override fun writeToParcel(parcel: Parcel, flags: Int) {
А есть плагин, который позволяет это не писать https://developer.android.com/kotlin/parcelize

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDto.kt
> +    override fun writeToParcel(parcel: Parcel, flags: Int) {
Вот тут еще поподробнее https://medium.com/geekculture/parcelize-in-kotlin-how-and-why-you-need-it-f33fa0212eed

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/TvShow.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Вот про это говорил. Если вынести в build gradle - то можно использовать эту константу тут. Тогда если урл для картинки поменяется - не нужно будет по всему приложению рефакторить, только в gradle

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private var client: OkHttpClient = OkHttpClient.Builder()
Вот тут можно сделать проверку Build.Config!=Release - чтобы в релизной сборке не было видно логов

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            .map { it.trim() }
Реализация верная - но не в том месте)
Лучше это сделаать прямо внутри SearchBar - чтобы наружу торчал метод возвращающий Observable и там же операторы фильтрации. Cмысл в том чтобы если появится экран с поиском то не дублировать одно и тоже

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +                MovieApiClient.apiClient.searchByQuery(API_KEY, "ru", it)
Тут можно добавить дефолтные аргументы прямо в интерфейсе ретрофитовском

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
SubscribeOn и ObserveOn повторяется, можно вынести например в extension - чтобы не писать постоянно оба оператора

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
SubscribeOn и ObserveOn повторяется, можно вынести например в extension - чтобы не писать постоянно оба оператора

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/MovieItem.kt
> +    com.squareup.picasso.Picasso.get()
Лучше этот экстеншн сделать более универсальным - чтобы они принимал урл картинки. Так мы снизим зависимость от MovieDto

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/MovieItem.kt
> +    com.squareup.picasso.Picasso.get()
view: ItemWithTextBinding - тут лишний. У нас же и так экстеншн для ImageView - тогда в аргументах оно лишнее.

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/MovieItem.kt
> +    com.squareup.picasso.Picasso.get()
Потому что можно будет вот так вызывать: view.imagePreview.loadImage("some_url")

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/ActorItem.kt
> +        Picasso.get()
Тут можно экстншн для ImageView использовать

2023-01-10 21:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/search/SearchFragment.kt
> +        bundle.putString("KEY_TITLE", movie.title)
В константы ключ нужно вынести "KEY_TITLE"

2023-01-14 13:27 UTC, eels911 commented on app/src/main/java/ru/androidschool/intensiv/ui/feed/FeedFragment.kt
> +            .observeOn(AndroidSchedulers.mainThread())
private fun <T>Single<T>.subObserve(arr: Single<T>):Single<T>{
      return  arr.subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
    }

2023-01-22 07:20 UTC, merged